name: Emde Fikri a.k.a. Maulida Dzul Fikri
markdown: kramdown
permalink: /:title
plugins:
  - jekyll-feed
  - jekyll-archives
jekyll-archives:
  enabled: []
  layout: archive
  permalinks:
    year: '/:year/'
    month: '/:year/:month/'
    day: '/:year/:month/:day/'
    tag: '/tag/:name/'
    category: '/category/:name/'